name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        shell: pwsh
        run: |
          go build -o queryx.exe  cmd/queryx/main.go
          tar  zcvf  queryx_test-1_windows_amd64.tar.gz  ./*.md LICENSE  queryx.exe
          md5sum queryx_test-1_windows_amd64.tar.gz > checksums.txt
      - name: Test
        run: cat checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: |
             checksums.txt
             queryx_test-1_windows_amd64.tar.gz
